### ISSUE TITLE
How do I actually run this on the KITTI dataset?

### ISSUE THREAD

**Issue by soulslicer** [VIS4ROB-lab/ccm_slam#12]
We are told to run

```
roslaunch ccmslam Client0_kitti_half_res.launch
```

But this just waits on this message

```
[ INFO] [1574114392.427121734]: Started CSLAM client node...
```

What exactly are we supposed to do? 

Where do I actually input the paths of the KITTI dataset?

**Comment by patriksc** [comment]
This mean the system is not getting input data. Once you have converted the KITTI images to a bagfile (see https://github.com/VIS4ROB-lab/ccm_slam/issues/5) you need to put the appropriate topic name in the launch file ("TopicNameCamSub") before playing the bagfile - then it should work.

**Comment by patriksc** [comment]
Closed - inactive
