### ISSUE TITLE
Communication controller (to simulate network issues)?

### ISSUE THREAD

**Issue by lesurp** [VIS4ROB-lab/ccm_slam#16]
Hi,

I tried enabling the network disturbance via the *communication controller* (mentioned  Sec 5.3) however it doesn't seem to be included in the repository?

I changed the line in the server launch file (`src/ccm_slam/cslam/launch/Server.launch`) to:
```xml
<arg name="dist" default="1"/>
```

However it appears there's no such node: 

```
ERROR: cannot launch node of type [ccmslam/ccmslamCommTestDisturber]: Cannot locate node of type [ccmslamCommTestDisturber] in package [ccmslam]. Make sure file exists in package path and permission is set to executable (chmod +x)
```

And grep'ing `ccmslamCommTestDisturber` does not return anything, making me wonder if this part is simply not in the repository at all?

Thanks!

**Comment by patriksc** [comment]
Hey lesurp

Yes, the communication controller is not part of the repository. Thanks for the feedback, we should have removed this from the launch file. Sorry for the inconvenience!

**Comment by lesurp** [comment]
No problem, although I was a bit hoping that you had only forgotten it as I was interested in trying that controller. If there's any open source basis that you've used to write it that I could use? Thanks!

**Comment by patriksc** [comment]
Closed - inactive
