### ISSUE TITLE
Doubt in static transform publisher

### ISSUE THREAD

**Issue by manthan99** [VIS4ROB-lab/ccm_slam#21]
The launch file for the EuroC Dataset includes the following static transformation-
`<node pkg="tf" type="static_transform_publisher" name="linkS0_broadcaster" args="0 0 5 -1.571 0 -2 world odomS0 100" />`

What is the reason for keeping the Roll as -2? Shouldn't it also be -1.571 since the camera is front-facing in the dataset? I am assuming that this will hardly affect the result unless comparing to the ground truth which is collected in the world frame. (for a custom dataset)

@patriksc

**Comment by patriksc** [comment]
Hi Manthan
The VI Sensor for EuRoC is front-down-looking, i.e. slightly tilted and not directly forward-looking. However, as you have already suspected, this only matters for the visualization - so feel free to change this to anything you find more convenient for inspecting the visualization.
