### ISSUE TITLE
complie error in jetson nano

### ISSUE THREAD

**Issue by buenos-dan** [VIS4ROB-lab/ccm_slam#23]
when using docker ros:melodic-ros-base,    I try to compile the ccmslam project with "catkin build ccmslam --cmake-args -DG2O_U14=0 -DCMAKE_BUILD_TYPE=Release",  then there is an error "c++: internal compiler error: Killed(program cc1plus)".
is any body try to compile this project in docker?

update date: 20/7/9: I use jetson nano to complie this project, I tried three method.
1. install ros directly in jetson nano,  and compile failed. (stuck in 17%）
2. install ros in ros:melodic-ros-base docker at jetson nano, and compile failed. (c++ internal compiler error)
3. install ros in ubuntu:18.04 docker and install ros in this docker at jetson nano, and compile failed. (stuck in17%)

many other errors have fixed already, but I really don't know how to fixed this situation above.
I guess arm64 is uncompatiable for ccm-slam project, so who have compiled successfully in jetson nano, Can anybody help me?

**Comment by txyxy** [comment]
I compiled this project in Ubuntu 16.04.

**Comment by buenos-dan** [comment]
problems are caused by samll memory, set a swapfile in jetson nano may fix this problem.

**Comment by patriksc** [comment]
Closed - inactive
