### ISSUE TITLE
Essential Graph not being used for GBA

### ISSUE THREAD

**Issue by manthan99** [VIS4ROB-lab/ccm_slam#25]
Hii

It is mentioned in the JFR publication that you are utilizing the Essential graph as done in ORB SLAM implementation for quicker GBA and for losing the redundant edges. I interpreted that changing the **Opt.EssGraphMinFeats** will change the criteria for building the **Essential Graph** from the **Covisibilty Graph**. The default value is **100**. I noticed a problem with this parameter. It seems that it is not being used.

An experiment was performed with 2 agents for 2 different runs and it was observed as follows-

Run 1. **Opt.EssGraphMinFeats = 100:**   Here it was kept as default value. As attached in the screenshot "**GBA_100.png**", the no. of Keyframes (Vertices) were **617** and the no. of edges were pretty high = **201005**. The no. of edges were relatively very high for 617 KFs and thus the optimization time was a whopping **57.188s**. 

Run 2. **Opt.EssGraphMinFeats = 200:**   I increased the value to **200**. As seen in the attached screenshot "**GBA_200_rviz.png**", a very few grey lines (Viewer.CovGraphMinFeats was also set to 200 which represent the grey lines) can be seen. But when we see the screenshot "GBA_200.png", the no. of Keyframes were **590** and the no. of edges were still high = **192063**. Thus, the optimization time was again very high.

Thus, I feel that there is some bug which is not causing the correct building of essential graph and thus it is not utilizing the Essential graph for GBA.

It would be great if you can look into this issue.
@patriksc 

Attachments-

1. GBA_100.png
![GBA_100](https://user-images.githubusercontent.com/36295915/88518551-4bea7e80-d00e-11ea-920d-f29c8d7e2da5.png)

2. GBA_200.png
![GBA_200](https://user-images.githubusercontent.com/36295915/88518554-4d1bab80-d00e-11ea-8e8d-fb853f165f6b.png)

3. GBA_200_rviz.png
![GBA_200_rviz](https://user-images.githubusercontent.com/36295915/88518558-4db44200-d00e-11ea-8ccd-a503f0311db7.png)

**Comment by patriksc** [comment]
Dear Manthan

The optimization is a 2-step approach: first, an essential graph optimization is performed, with the goal to bring the estimate closer to the optimum, which then speeds up the second step, the GBA, since not all the work needs to be done by the (computationally more expensive) GBA. GBA always takes into account all Keyframes and Landmarks, therefore the parameters for the essential graph do not directly affect the number of edges that are established in GBA run.
