### ISSUE TITLE
Problem in running slam on client.

### ISSUE THREAD

**Issue by harisbuilds** [VIS4ROB-lab/ccm_slam#29]
Hello. 
I was trying to execute ccm slam on my local machines. I was successfully able to connect client with server. I made all necessary updates required to use my pc's usb cam with the code. No when I launch my usb cam it doesn't show any thing. 

Kindly guide me in solving this issue.

**These are my client and server in running state:**

![Screenshot from 2021-04-28 14-10-15](https://user-images.githubusercontent.com/54216004/116378625-c1001400-a82b-11eb-8c1a-66077a70d41e.png)
![Screenshot from 2021-04-28 14-10-59](https://user-images.githubusercontent.com/54216004/116378631-c2c9d780-a82b-11eb-9962-345c715252c6.png)

**Then as soon as I open my web cam I get this issue:**
![Screenshot from 2021-04-28 14-11-05](https://user-images.githubusercontent.com/54216004/116378836-ec82fe80-a82b-11eb-8f7a-6433001376a4.png)

**This is my client file:**
![Screenshot from 2021-04-28 14-11-42](https://user-images.githubusercontent.com/54216004/116378903-fa388400-a82b-11eb-84ce-05222f92b5ea.png)

@patriksc please if you can help.

**Comment by harisbuilds** [comment]
Solved it.

**Comment by banciuadrian** [comment]
If I may ask, how did you go about fixing this?

**Comment by aliasboink** [comment]
If I may ask, how did you go about fixing this issue?

**Comment by harisbuilds** [comment]
@banciuadrian I changed the order of executing my files. I used to first execute client and then my usb cam. When I switched their order, it started working perfectly fine. I did a lot of debugging to figure out why it does that but was unable to find a good supporting logic.

**Comment by flyover-26** [comment]
@Haris-Ali007 Hi!
I test this system with d435i.And I just run one agent.And I found it very easy to tracking:lost if I move camera a little bit faster.
Have you got the same problem?How do you fix it?
thank you!Looking forward to your reply!
