### ISSUE TITLE
Error in trying to launch any launch file.

### ISSUE THREAD

**Issue by laibazahid26** [VIS4ROB-lab/ccm_slam#31]
Hello,
I built this project successfully. But when I try to launch the server I get the error below:

![error](https://user-images.githubusercontent.com/58592667/124010795-9410de80-d9df-11eb-95be-6c8b5246d72a.jpg)

This error does not tell anything much about the issue. I don't understand where to look to debug it. 
I am using Ubuntu 18.04 and the processor is AMD Ryzen 7. I have 12 GBs of memory.

**Comment by ans-qureshi** [comment]
Hi @laibazahid26 I am facing the same problem, how did you resolve this?
![image](https://user-images.githubusercontent.com/38855178/124384796-6a5ffc00-dcec-11eb-9097-79d119fe3d1f.png)
![image](https://user-images.githubusercontent.com/38855178/124384837-8c597e80-dcec-11eb-8b23-3ad1584596fa.png)

**Comment by laibazahid26** [comment]
Hi, 
I think you are launching the Client in the wrong way. You need to type 
**roslaunch ccmslam Client0_euroc.launch**
inorder to launch Client 0. 

However, my problem was different. I still do not understand the reason for this error. But I uninstalled Ubuntu and installed Docker (on my Windows) on my laptop and installed Ubuntu image on Docker. And everything ran perfectly.

**Comment by laibazahid26** [comment]
> Hi @laibazahid26 I am facing the same problem, how did you resolve this?
> ![image](https://user-images.githubusercontent.com/38855178/124384796-6a5ffc00-dcec-11eb-9097-79d119fe3d1f.png)
> ![image](https://user-images.githubusercontent.com/38855178/124384837-8c597e80-dcec-11eb-8b23-3ad1584596fa.png)


Hi,
I think you are launching the Client in the wrong way. You need to type
roslaunch ccmslam Client0_euroc.launch
inorder to launch Client 0.

However, my problem was different. I still do not understand the reason for this error. But I uninstalled Ubuntu and installed Docker (on my Windows) on my laptop and installed Ubuntu image on Docker. And everything ran perfectly.

**Comment by ans-qureshi** [comment]
@laibazahid26 no, I renamed the launch file. Anyways, i'll try some other way. Thanks!

**Comment by emily-68** [comment]
> Hello, I built this project successfully. But when I try to launch the server I get the error below:
> 
> ![error](https://user-images.githubusercontent.com/58592667/124010795-9410de80-d9df-11eb-95be-6c8b5246d72a.jpg)
> 
> This error does not tell anything much about the issue. I don't understand where to look to debug it. I am using Ubuntu 18.04 and the processor is AMD Ryzen 7. I have 12 GBs of memory.

Hello, I also encountered this problem. I modified CMakeLIst,This problem is due to the OpencV version,You need to modify the file"/home/siat/twq_ws/ccm_slam/src/ccm_slam/cslam/CMakeLists.txt",  find_package(OpenCV 3 REQUIRED)，Please do not use OPencv 2.4.13
