### ISSUE TITLE
is it easy to change monoslam->rgbdslam?

### ISSUE THREAD

**Issue by kimwin2** [VIS4ROB-lab/ccm_slam#4]
hi, 
Nowadays, we are trying to build multi-robot SLAM system.
Our usage is based on RGBD sensor, which is different from ccm_slam(mono slam).
Do you think is it easy to convert CCM SLAM from monoslam to RGBD slam?

Thanks. 
I really appreciate your affort.

**Comment by patriksc** [comment]
I think it should be possible to keep the same structure and architecture for RGBD-SLAM. However, it would be necessary to adapt the modules and structures (keyframes, messages, optimization etc.) to the RGBD approach. I would assume you need to put some work in the implementation, but CCM-SLAM could provide a good starting point that you can extend towards RGBD.

**Comment by cai199626** [comment]
@kimwin2 I want to know your progress of rgbd-ccm_slam, we also want to do the same thing. If you succeed,  please let me know! or there are some difficulies? Thanks a lot!

**Comment by liyuting-123** [comment]
@kimwin2
I am learning this knowledge. I also want to know your progress of rgbd-ccm_slam. If you succeed, please let me know! or there are some difficulies? Thanks a lot!

**Comment by sun1f** [comment]
@kimwin2 
I am learning this knowledge. I also want to know your progress of rgbd-ccm-slam. If you succeed, please let me know! or there are some difficulies? Thanks a lot!
