### ISSUE TITLE
Error in kitti.yaml files

### ISSUE THREAD

**Issue by DanielRoeder1** [VIS4ROB-lab/ccm_slam#45]
A slight error in the config files resulting in the output trajectories not being written correctly.

From https://github.com/VIS4ROB-lab/ccm_slam/issues/11 it is apparent that the T_SC matrix in the config.yaml files should be set to the identity matrix if there is no conversion between the camera and sensor frame.

The T_SC matrix in the kitti.yaml files is not correctly set resulting in the following matrix:

[1 0 0 0]
[0 1 0 0]
[0 0 0 1]
[0 0 0 1]

As this matrix has no inverse, the resulting trajectory files (KF_GBA.csv) will contain only nan values.

Fix: 
#T_SC
Cam0.T00: 1.0
Cam0.T01: 0.0
Cam0.T02: 0.0
Cam0.T03: 0.0
Cam0.T10: 0.0
Cam0.T11: 1.0
Cam0.T12: 0.0
Cam0.T13: 0.0
Cam0.T20: 0.0
Cam0.T21: 0.0
Cam0.T22: 1.0
Cam0.T23: 0.0
Cam0.T30: 0.0
Cam0.T31: 0.0
Cam0.T32: 0.0
Cam0.T33: 1.0

**Comment by patriksc** [comment]
Thanks for the feedback Daniel - good catch, you are of course right here. Fixed by a44604781a6ff40c554e4d3635715420449412e5
