### ISSUE TITLE
How to determine the coordinate system of each agent's pose information?

### ISSUE THREAD

**Issue by zhouleiqiang** [VIS4ROB-lab/ccm_slam#46]
Hello, I would like to ask how the coordinate system of CCM-SLAM is determined. Is the pose information of all agents based on the first agent coordinate system? Then merge the maps by closing the loop? Is my understanding right? Looking forward to your reply.

**Comment by patriksc** [comment]
Yes, your understanding is (almost) be correct. For each individual map (before any merge happens), the coordinate system is defined by the first keyframe (KF0) of that map. If two maps merge (let's say `merge(A,B)`), `B` is transformed in to the coordinate frame defined by `A` and adopts it. However, that also means if a merge happens as `merge(second agent, first agent)`, the global coordinate system would be the one of the second agent.

**Comment by zhouleiqiang** [comment]
> 

Thank you very much for your reply！
