### ISSUE TITLE
Memory consumption is too large

### ISSUE THREAD

**Issue by flyover-26** [VIS4ROB-lab/ccm_slam#51]
hi！I test ccm on kitti and I noticed that when dataset run for 3/4  it need memory about 9g while orb-slam2 only cost 3g.I have no idea why it need so much memory(It should not be related to the number of KF ,because it has almost the same number of KF as orb-slam2).And it need more than 20g when I change it to stereo-version which is to large for my computer.
 Is there any reason may result in this?Looking forward to your reply!

**Comment by patriksc** [comment]
Hi! We have not in particularly analyzed the memory footprint of CCM-SLAM, so I cannot say exactly why you see a significant difference compared to ORB-SLAM. I would probably recommend to quickly use a profiler to see whether there are some memory hotspots that can be easily reduced.

**Comment by patriksc** [comment]
Closed - inactive
