### ISSUE TITLE
cannot run client and server on two PC

### ISSUE THREAD

**Issue by JoannaZhj** [VIS4ROB-lab/ccm_slam#55]
Hi, I have followed the steps and it's OK to perform both client and server on one PC. After I use two PCs and execute the ROS_MASTER_URI in terminal, client performs well. But server cannot show the map. Do I miss something? I'm sure that two PCs connect to the same wifi.
Thanks for your help!

**Comment by patriksc** [comment]
Sorry for the late answer! Maybe you also have to set the local ROS IP as well with `export ROS_IP=<your-local-IP>` (in each terminal, use on each PC local IP)
I would recommend following a tutorial implementing a simpler interaction than a full collaborative SLAM system here, to make sure everything is OK and correctly set up. If that works, but you still don't get a connections between the agents and the server, please let us know. Here's some pointers to tutorials:
- https://wiki.ros.org/ROS/Tutorials/MultipleMachines
- https://github.com/husarion/static_docs_deprecated/blob/master/src/core2/tutorials/ros-tutorials/5-running-ros-on-multiple-machines.md

**Comment by JoannaZhj** [comment]
OK, I'll give it a try.Thank you very much.

Patrik Schmuck ***@***.***> 於 2022年10月29日 週六 21:32 寫道：

**Comment by patriksc** [comment]
Closed - inactive
