### ISSUE TITLE
Problems about changing ccm-slam to rgbd version

### ISSUE THREAD

**Issue by Janebekk** [VIS4ROB-lab/ccm_slam#56]
Hi! @patriksc 

I've been trying to change ccm-slam to rgbd version, I changed some codes according to ORB2-SLAM.

I think I changed it right. But now a strange thing happend, I can successfully run this rgbd version on the terminal side, however I have nothing visualized on the Rviz side.(As shown below) 

![微信图片_20221005230716](https://user-images.githubusercontent.com/115089830/194096743-95c3187b-ffbc-4701-b705-5069df27bdc8.jpg)

I don't know why is this hapening.

Can you please help me on this, thank you so much!  Really looking forward to your relpy!

**Comment by sun1f** [comment]
@Janebekk 
Dear friend, I am learning this knowledge, too. I also want to know your progress of "ccr_slam". can you please share your code with me?
Thanks a lot!
