### ISSUE TITLE
Tracking Lost

### ISSUE THREAD

**Issue by ProKaroly** [VIS4ROB-lab/ccm_slam#59]
If !!! +++ Tracking: Lost +++ !!! error message appears. Is the VO node (agent node) can not relocalize itself? For example:  if ORB-SLAM3 "tracking lost" error message occurs: after 5 seconds it creates a new map and it can later merge the new map with the previously created map. (If the area where the track is lost is revisited). But when CCM-SLAM agent node, lost tracking it does not do anything, just stuck in lost tracking state.

**Comment by patriksc** [comment]
Hi, thanks for your feedback.Tracking recovery is unfortunately so far not implemented in CCM-SLAM, yes.  I agree with you that it would be a very useful addition to the system, but we are currently not actively extending CCM-SLAM, so there are no plans in this direction as of now.

**Comment by patriksc** [comment]
Closed - inactive
