### ISSUE TITLE
Is it possible for server to save map?

### ISSUE THREAD

**Issue by kimwin2** [VIS4ROB-lab/ccm_slam#6]
Hi, 
I really thank you for your reply.
I have one more question.

ccm slam can save map on server?
and can we load map on client?

I want to make a system which can save map on server and load map on client.

I reallly thank you for your reply.
thanks.

**Comment by patriksc** [comment]
Hi 

At the moment, there isn't any functionality like this implemented. However, some time ago I was testing a function to save and load maps on the server, that then could be merged with other, new maps during the mission.

What do you want to do with the loaded map on the client side? The loading functionality was designed for the server, not for the client to re-localize against this map. However, depending on what you want to achieve, this could maybe serve as a starting point for you, that you can adapt.

Best
Patrik

**Comment by arindamsaha81** [comment]
Hello,

Can you please provide me the source code for the function to save the map on the server?

Regards,
Arindam

**Comment by patriksc** [comment]
Function available in devel branch
