### ISSUE TITLE
The number of estimated poses output by CCM-SLAM is not equal to the total number of frames. Which frames are the poses it outputs?

### ISSUE THREAD

**Issue by TwiceMao** [VIS4ROB-lab/ccm_slam#63]
The number of estimated poses output by CCM-SLAM is not equal to the total number of frames. Which frames are the poses it outputs?

**Comment by patriksc** [comment]
I assume you are referring to the output files such as `KF_GBA_<AGENT_ID>.csv`, correct?  CCM-SLAM outputs only the poses of the **keyframes**, not for each individual frame from the input image stream.

**Comment by patriksc** [comment]
Closed - inactive
