### ISSUE TITLE
About the function SetPoseFromMessage

### ISSUE THREAD

**Issue by markinruc** [VIS4ROB-lab/ccm_slam#65]
Dear author:

Why does the server use the pose change of the parent to set the pose of the keyframe when creating it by msg, and why not directly transmit Tcw in KF.msg
I am quite confused when reading the code.
Thank you very much for your answer.

**Comment by patriksc** [comment]
Hello markinruc, thanks for your question. The logic behind the pose communication scheme, including the relative pose approach, is described in detail in the [paper](file:///home/pschmuck/Downloads/2018_CCM_SLAM.pdf), in section 4.5.
